##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [5]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a+b)
print(a-b)
print(a//b)
print(a*b)

[11 22 33 44]
[ -9 -18 -27 -36]
[0 0 0 0]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [6]:
a = np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b*5)

[[ 5 10 15]
 [20 25 30]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [9]:
arr = np.array([6,43,23,87,21,0,-1])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
print(np.mean(arr))

179
-1
87
28.903075184174448
835.3877551020408
25.571428571428573


You can also do the axis based operations row-Wise and Colum-wise

In [10]:
data = np.array([[1,2,3],[4,5,6]])


In [14]:
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))
print(np.mean(data,axis=1))
print(np.mean(data,axis=0))

[ 6 15]
[5 7 9]
[2. 5.]
[2.5 3.5 4.5]
