# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros([10,3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full([5,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,5)

array([[0.99741787, 0.35210252, 0.71280594, 0.34612857, 0.23143235],
       [0.88552524, 0.72886362, 0.13871234, 0.09616721, 0.01202903],
       [0.27809379, 0.72292818, 0.03168818, 0.61194424, 0.61210465],
       [0.46500117, 0.02811237, 0.0180907 , 0.81020804, 0.12221985],
       [0.85428419, 0.51372668, 0.24891879, 0.49722804, 0.39326761]])

In [ ]:
np.random.randint(1,10,10)

array([3, 7, 2, 5, 9, 5, 7, 2, 7, 5])

In [ ]:
np.random.randint(1,10,(3,3))

array([[5, 2, 5],
       [7, 6, 9],
       [7, 4, 6]])

In [ ]:
np.random.randn(2,4)

array([[ 0.19482481, -0.01965912,  0.73928781,  0.41524407],
       [ 0.85330809,  0.38677958, -1.27016023,  1.04142608]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution