##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
a[[1,5,3]]

array([2, 6, 4])

You can do this fancy indexing in 2D Matrix aswell

In [15]:
mat = np.arange(1,13).reshape(3,4)
print(mat)
mat[[0,1,2],[1,2,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 2,  7, 12])

##Conditional Selection
Find values based on conditions or replace them.

In [24]:
b = np.array([1,2,3,4,5,6,7])
# print(b[b>2])
np.where(b>3,b,0)

array([0, 0, 0, 4, 5, 6, 7])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [25]:
c = np.array([6,3,4,1,0,-2])
np.sort(c)

array([-2,  0,  1,  3,  4,  6])

In [26]:
np.argsort(c)

array([5, 4, 3, 1, 2, 0])

##Concatenation & Stacking

In [28]:
x = np.array([1,2,3])
y = np.array([4,6,7])
np.concat([x,y])

array([1, 2, 3, 4, 6, 7])

Vertical & Horizontal Stacking

In [29]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [30]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
np.hstack((B,A))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [33]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])