##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [5]:
import numpy as np
a = [[1,2,3],[4,5,6]]
arr = np.array(a)

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [7]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])

1
6


Now lets see the 2D indexing aswell

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[2][2]

np.int64(9)

Now we can also do the slicing lets see the **slicing in 1D**

In [19]:
a = np.array([1,2,3,4,5])
# a[:3]
a[2:]

array([3, 4, 5])

1D slicing was really easy now lets see the **slicing in 2D**

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr[0:2,0:2]
arr[1:,1:]

array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [25]:
arr = np.array([5,10,15,20,25])
print(arr[arr>12])   #Boolean Indexing

[15 20 25]


In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[arr>=5]

array([5, 6, 7, 8, 9])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [34]:
a1 = np.arange(1,31).reshape(5,6)
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [36]:
a1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])